# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calc_props_pb2 as calc__props__pb2


class PropServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProp = channel.unary_unary(
                '/props.PropService/CreateProp',
                request_serializer=calc__props__pb2.CreatePropsRequest.SerializeToString,
                response_deserializer=calc__props__pb2.CreatePropsResponse.FromString,
                )
        self.ReadProp = channel.unary_unary(
                '/props.PropService/ReadProp',
                request_serializer=calc__props__pb2.ReadPropsRequest.SerializeToString,
                response_deserializer=calc__props__pb2.ReadPropsResponse.FromString,
                )
        self.UpdateProp = channel.unary_unary(
                '/props.PropService/UpdateProp',
                request_serializer=calc__props__pb2.UpdatePropsRequest.SerializeToString,
                response_deserializer=calc__props__pb2.UpdatePropsResponse.FromString,
                )
        self.DeleteProp = channel.unary_unary(
                '/props.PropService/DeleteProp',
                request_serializer=calc__props__pb2.DeletePropsRequest.SerializeToString,
                response_deserializer=calc__props__pb2.DeletePropsResponse.FromString,
                )
        self.ListProp = channel.unary_unary(
                '/props.PropService/ListProp',
                request_serializer=calc__props__pb2.ListPropsRequest.SerializeToString,
                response_deserializer=calc__props__pb2.ListPropsResponse.FromString,
                )


class PropServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProp': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProp,
                    request_deserializer=calc__props__pb2.CreatePropsRequest.FromString,
                    response_serializer=calc__props__pb2.CreatePropsResponse.SerializeToString,
            ),
            'ReadProp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProp,
                    request_deserializer=calc__props__pb2.ReadPropsRequest.FromString,
                    response_serializer=calc__props__pb2.ReadPropsResponse.SerializeToString,
            ),
            'UpdateProp': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProp,
                    request_deserializer=calc__props__pb2.UpdatePropsRequest.FromString,
                    response_serializer=calc__props__pb2.UpdatePropsResponse.SerializeToString,
            ),
            'DeleteProp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProp,
                    request_deserializer=calc__props__pb2.DeletePropsRequest.FromString,
                    response_serializer=calc__props__pb2.DeletePropsResponse.SerializeToString,
            ),
            'ListProp': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProp,
                    request_deserializer=calc__props__pb2.ListPropsRequest.FromString,
                    response_serializer=calc__props__pb2.ListPropsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'props.PropService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PropService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/props.PropService/CreateProp',
            calc__props__pb2.CreatePropsRequest.SerializeToString,
            calc__props__pb2.CreatePropsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/props.PropService/ReadProp',
            calc__props__pb2.ReadPropsRequest.SerializeToString,
            calc__props__pb2.ReadPropsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/props.PropService/UpdateProp',
            calc__props__pb2.UpdatePropsRequest.SerializeToString,
            calc__props__pb2.UpdatePropsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/props.PropService/DeleteProp',
            calc__props__pb2.DeletePropsRequest.SerializeToString,
            calc__props__pb2.DeletePropsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/props.PropService/ListProp',
            calc__props__pb2.ListPropsRequest.SerializeToString,
            calc__props__pb2.ListPropsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
